tasks:
  - name: "Creating symbolic links."
    ansible.builtin.file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    with_items:
      # - { src: "foo", dest: "FOO" }
